### PR TITLE
remove cache directories later

### PR DESCRIPTION
**Pull request by vn971**

### CODE REVIEW

**Comment by vn971** [comment]
This will fix early cache removal issue from https://github.com/vn971/rua/issues/28

**Comment by vn971** [comment]
Sorry for pushing more commits after the PR was already opened. Understood that I want to fix a few things in same PR first.

A better and/or long-term solution would probably not to mess up with PKGDEST and the "target" subdirectory at all. For that RUA needs to teach itself how to deal with split packages and versions first though. So currently the intent is to wipe out whole dirs if it can help avoiding conflicts/mismatches.

**Comment by vn971** [comment]
@Morganamilo hi, did you have any thoughts on the PR-s yet? If there's a chance that you'll have some time on the week, I'd wait. If you know you won't have any, I'd merge.
Thoughts?

**Comment by Morganamilo** [comment]
Assuming the title is correct why remove them later? Why not just not remove them at all?

**Comment by vn971** [comment]
@Morganamilo because there is no built-in automated way to upgrade packages, at least not yet. Having clean build directory is what I'd like to have even for future. E.g. even if we show upstream git diff, I would still prefer to copy the edited AUR repo to a separate dir and build there cleanly. Does that make sense to you?

**Comment by Morganamilo** [comment]
That's fine enough then I guess. I don't really know how rua builds things in the first place so there's not much point in me reviewing. And like I said I hate the official approval stuff.

**Pull request merged**
