### PR TITLE
[DRAFT] Re-factor `tar_check` and SandboxOpts

### PR DESCRIPTION
**Pull request by VukoDrakkeinen**
So, uh, I went a _little bit_ overboard with **reckless refactoring** while fixing the bug ¯\\\_(ツ)_/¯

I'm not sure I want to merge it as is, really, but here it is just in case.
Alternate (simpler!) take: #116

Thoughts?

### CODE REVIEW

**Comment by VukoDrakkeinen** [comment]
I'm going to post some explanatory comments tomorrow,
which should make this PR (hopefully) more digestible.

**Comment by vn971** [comment]
Can you please explain a bit on the underlying issue itself? E.g. you try to do what, and what breaks?

**Comment by VukoDrakkeinen** [comment]
> Can you please explain a bit on the underlying issue itself? E.g. you try to do what, and what breaks?

Ah, sorry, I shouldn't have removed the commit message from the PR itself.

As you might know by now, I have a bit of a unique setup with my `$XDG_CACHE_HOME`.
Building any VCS package with `rua` on my system would always emit a warning:
```
==> WARNING: PKGBUILD is not writeable -- pkgver will not be updated
```
and I would get the stale package version.

I tracked this down to a working dir & bind mounted dir paths mismatch.
Turns out, that `chdir()` internally canonicalises the path, so in the end
`$PWD != $pkgbuild_dir` (in `bwrap --bind $pkbuild_dir $pkgbuild_dir`)
and Bubblewrap blocks write access.

The fix is to eagerly canonicalise the path when passing it to `wrap.sh`.

...and then I got extremely carried away while making minor clean-ups
in `wrapped.rs` :d

**Comment by VukoDrakkeinen** [comment]
Honestly, the more I look at this PR, the less ready it looks. :|
I think I'm going to try to polish it over the coming week, splitting stuff
into separate commits and such.

**Comment by VukoDrakkeinen** [comment]
We might want to think about merging #116 as a hotfix, though.

**Comment by vn971** [comment]
Yes, exactly that:
> splitting stuff
> into separate commits and such

Can you do that? Would be very helpful. I can merge the fix itself though.. Which I'll try to do delaying my sleepiness now.

**Comment by vn971** [comment]
Closing due to inactivity.
Feel free to return to this and re-open, should there be time for this PR later.

**Pull request closed without merging**
