### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by Morganamilo**

### CODE REVIEW

**Comment by vn971** [comment]
Hey, thanks! Do you run clippy under a stricter settings than default to get these warnings? I have clippy as part of CI and manual release procedure, but I didn't see those warnings yet.

**Comment by Morganamilo** [comment]
I use the defaults. But I am on nightly, so maybe they're new lints.

**Comment by vn971** [comment]
Could be it. Thanks!

P.S. Also noticed that `cargo clippy -- -W clippy::pedantic` gives some more warnings, some of which I could agree to. Maybe the project could enforce those as well. (Will take a look at that after finishing my current WIP branch that I have locally)

**Comment by Morganamilo** [comment]
I find pedantic to be a bit too far. Sometimes may run it just to see what it spits out and if i agree with any of the lints. But enforcing all of them I think is too far.

**Pull request merged**
