### PR TITLE
Use correct arch

### PR DESCRIPTION
**Pull request by Morganamilo**
This was fixed in c76710a8 then later unfixed in fc548e3f.

### CODE REVIEW

**Comment by vn971** [comment]
Do you have any evidence that `libalpm`-s "arch" is wrong?

**Comment by vn971** [comment]
It uses just the OS architecture instead of things defined in pacman.conf, right?

**Comment by Morganamilo** [comment]
See #9.

https://github.com/vn971/alpm/blob/fork/libalpm/src/util.rs#L9 It's just a wrapper around uname and not related to libalpm at all. I don't really get why it's in there to be honest.

**Comment by vn971** [comment]
Yeah was just about to check the same. Thanks! Merging.

**Comment by vn971** [comment]
Merged. Not making a new release yet as I'm on a vacation with bad internet -- will do later.

**Comment by Morganamilo** [comment]
Also speaking of libalpm. I have my own more complete bindings here: https://github.com/Morganamilo/alpm.rs.

Which I make try and push here some time at some point.

**Comment by Morganamilo** [comment]
Although I do plan use it to write a depsolver first. So probably after then.

**Comment by vn971** [comment]
Interesting! That's a lot of work though. But I don't know how to write bindings and how good it is to fork/rewrite, so I'll just monitor the situation for now.

I'm pretty open to moving to alpm.rs if there'll be any benefits though :+1:

**Comment by Morganamilo** [comment]
The current bindings are not fully complete and have `unimplemented!()` all over. Also as noted in the readme, the bitfields enums are not properly handled, so it's impossible to do a lot of things right.

I originally started trying to make a depsolver a while ago using these bindings. Had issues and looked into patching them, then decided to just start over.

I've already patched rua to use my bindings, and it works as is apart from some function name changes.

But I'm not gonna make a PR for it now at least. If I can make a good depsolver and want to integrate it into rua, then rua would need to use the same alpm bindings as my depsolver.

**Pull request merged**
