### PR TITLE
Clippy fixes

### PR DESCRIPTION
**Pull request by senden9**
Hi!

I want to implement a search with results in the terminal. For that I first fixed all clippy lints as seen in the first commit of this PR. The most "fixes" are just [expect_fun_call](https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call) things. So you basically save one `format` call that is unnecessary the most time.

Let me know how you think about that changes!

### CODE REVIEW

**Comment by vn971** [comment]
// Preliminary comment. Thanks! I'll return to it tomorrow or on the week.

**Comment by vn971** [comment]
// Added the check as part of CI as well. For both rustfmt and clippy.

**Comment by senden9** [comment]
I did them by hand. I think i heard from some `rustfix`-tool or something like that that can do things like this automatically. But when it comes to codebase changes like this i review the things "by hand" and look if the changes make sense. From time to time clippy has false positives.

**Comment by vn971** [comment]
I see. Thanks a lot for the contribution!

**Comment by vn971** [comment]
BTW, I noticed that some errors are swallowed in the newer rewrite if we use:
`result.unwrap_or_else(|_| panic!("")`

Something that `expect` handled better actually, because it has shown the underlying reason. I think this re-write is OK though:
`result.unwrap_or_else(|err| panic!("blah blah blah, err: {}", err)`

Didn't play out with yet, especially regarding how exactly the error would be displayed, but I think it should work. I've raised a PR with the change: https://github.com/vn971/rua/pull/23

**Pull request merged**
