### PR TITLE
improve error logging for Result.unwrap_or_else

### PR DESCRIPTION
**Pull request by vn971**

### CODE REVIEW

**Comment by vn971** [comment]
@Morganamilo pretty boring PR I guess.🤷‍  I hope to push some more interesting PR-s in the future!

**Comment by vn971** [comment]
BTW, if any particular PR seems boring enough and you don't want to read it through -- you don't have to, just tell and I'll skip it (merge manually).

**Comment by vn971** [comment]
Regarding `line!()` and panicking -- rust only gives really useful stack traces if debugging symbols aren't stripped off. They are, however, stripped by `makepkg` by default. If the user builds "rua" package as-is, stack trace will be very limited and line numbers won't be visible. There are some language proposals in Rust that would ease up this `file!()` and `line!()` nonsense, but currently that's what you must do if debugging symbols are stripped off and you want line numbers, apparently..

I'll think more about the nicer error formatting -- good question indeed.

**Comment by Morganamilo** [comment]
That makes sense then. Also failure has a back trace feature. Not sure if it's effected by stripping though.

**Comment by vn971** [comment]
Thought of addressing the linked issue ("better logging") along the way, but let's do it consecutively.

**Comment by vn971** [comment]
merged.

**Pull request closed without merging**
