### PR TITLE
check bwrap availability

### PR DESCRIPTION
**Pull request by vn971**
In case of error, exit with a nicer message

### CODE REVIEW

**Comment by Morganamilo** [comment]
Not sure what the point of this is. Seems like this is what `depends=()` is for.

**Comment by vn971** [comment]
@Morganamilo no, it's meant as a different thing. `depends=()` checks package availability. Some files lying around on filesystem.

This code, however, is meant to test whether it actually works. Like in docker https://github.com/vn971/rua/issues/8

Easiest way to test:
`bwrap --dev-bind / / rua install test`
The command `rua install test` will then be run inside a jail. It wil fail at run-time. With this PR, there'll be a clear explanation why it fails.

**Comment by Morganamilo** [comment]
Oh right I skimmed it and only saw the `bwrap binary not found` message.

**Comment by vn971** [comment]
@Morganamilo yes, that's exactly what I'm expecting. (Wouldn't mind anything else, but I'm realistic.:)

**Pull request merged**
