### PR TITLE
use srcinfo information to improve "builddir" action

### PR DESCRIPTION
**Pull request by vn971**
use srcinfo information to improve "builddir" action
    
also, add support for --force key of makepkg

### CODE REVIEW

**Comment by vn971** [comment]
The internal goal is to introduce SRCINFO parsing for newly built packages, allowing to refactor the current `archive_whitelist`.

**Comment by Morganamilo** [comment]
Don't you want to use `--packagelist` for this?

**Comment by vn971** [comment]
@Morganamilo it could be done indeed. But won't we need more information in the future? For example, if we'd like to just re-generate the version of the PKGBASE in the future.

**Comment by Morganamilo** [comment]
`--packagelist` includes the version number too. The advantage of `--packagelist` is it gives you the true path to the package. This allows you to support `PKGDEST` and `PKGEXT`. Both of which I have configured and are annoyingly overridden by rua.

**Comment by vn971** [comment]
@Morganamilo so you have those environment variables set, and rua overrides them? Do you mean to say that this code is broken?: https://github.com/vn971/rua/blob/4c86fb1cd4a62c30c395c1a2fbd6a17de301d62a/src/rua_environment.rs#L56

**Comment by Morganamilo** [comment]
No, I have them configured via `makepkg.conf` so they're never in the environment. But because rua sees them as unset, it sets them itself. Which overrides my `makepkg.conf` as the environment takes priority.

**Comment by vn971** [comment]
Interesting, I wasn't aware of this situation. So we can

* teach the client to read makepkg.conf regarding these values, and give read-write access to this directory. That would mean that it won't be isolated between runs and across packages.

* or we can ignore those variables, but do it explicitly, as a design choice rather than accident.

I'll think tomorrow or on the weekend with a clear mind (now it's late).

**Comment by Morganamilo** [comment]
From the perspective of a user. I don't care if it's on purpose or not. I would like my config to be respected.

**Comment by vn971** [comment]
@Morganamilo until RUA starts to move built artifacts to PKGDIST, I've made the current contract exclicit (and also enforcing it) now. In the last commit..

**Comment by vn971** [comment]
Moving already built packages to PKGDIST wouldn't contradict with isolation though, so that's something that can be done in the future.. As far as I understood it so far, the way to go would be to use makepkg "library" (bash) interface and aquire the correct PKGDIST from there.

**Pull request merged**
